# Declaration of Authorship {.unnumbered .unlisted}

[https://www.hs-bremen.de/assets/hsb/de/Dokumente/ZLL/MMCC/declaration\_indep\_work\_Nov\_2024\_Form.pdf](https://www.hs-bremen.de/assets/hsb/de/Dokumente/ZLL/MMCC/declaration_indep_work_Nov_2024_Form.pdf)

We hereby certify that we have written this thesis independently and have not used any sources or aids other than those
specified. Sources and aids other than those indicated. The passages in the thesis that have been taken from other works
in terms of wording or meaning are from other works are identified as such.

This statement also applies to the graphics, sketches and illustrations contained in the thesis. We have not already
submitted the work in the same or a similar form, including extracts, as part of an examination or coursework.


We hereby certify that the electronic version of the dissertation submitted is a complete copy of the printed version.
and agree to an electronic check of the thesis using plagiarism software.

Please tick the box:
One of the two options must be chosen in consultation between the assessor and the assessee.

-   [ ] Option 1: Use of AI-based tools without mandatory labelling
    We confirm that we have not used any AI-based tools whose use has not been agreed in writing with the verifier.
    We understand that the use of text or other content and products generated by AI-based tools is not a guarantee of
    their quality. We accept responsibility for the work submitted and the content contained therein. We also assure you
    that our creative influence predominates in this work.

-   [ ] Option 2: Use of AI-based tools with mandatory labelling
    We confirm that we have not used any AI-based tools whose use has not been agreed in writing with the verifier.
    We understand that the use of text or other content and products generated by AI-based tools is not a guarantee of
    their quality. We accept responsibility for the work submitted and the content contained therein. We also assure you
    that our creative influence predominates in this work. All verbatim or analogous adaptations and quotations, and all
    sections designed, written and/or edited using AI-based tools, will be marked and checked by us. The form of marking
    will be agreed between the examiner and the examinee.

We are aware that failure to comply with the above may have consequences in terms of examination law, and in particular
may result in the examination being marked &rsquo;insufficient&rsquo; or the coursework being marked &rsquo;failed&rsquo; and, in the case of
multiple or serious attempts to cheat, may result in my being de-registered.

First name and surname:

Matriculation number:

Date:

Signature:


First name and surname:

Matriculation number:

Date:

Signature:
