project:
  type: manuscript

manuscript:
  article: index.qmd

execute:
  freeze: auto

format:
  html:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    
  pdf:
    documentclass: scrreprt # scrartcl
    # lof: true
    # lot: true
    toc: true

    # keep-tex: true
    pdf-engine: xelatex
    
    papersize: a4 
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded

    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    
    biblio-style: ieee
    
    mainfont: "Calibri"
    fontsize: 11pt