project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    # mainfont: Helvetica Neue, Helvetica, Arial, sans
    # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    # backgroundcolor: "white"
    # fontcolor: "black"
    highlight-style: github

  pdf:
    documentclass: scrartcl
    # classoption: [twoside]
    keep-tex: true

    papersize: a4
           
    # geometry:
      # - inner=3cm
      # - outer=4cm
      # - top=2.5cm
      # - bottom=2.5cm
      # - left=3cm
      # - right=1.5cm
      # - headsep=22pt
      # - headheight=11pt
      # - footskip=33pt
      # - ignorehead
      # - ignorefoot
      # - heightrounded

    hyperrefoptions: 
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"

    fontsize: 11pt
    pdfengine: xelatex

    # Fonts
    # mainfont: "Latin Modern Roman"
    # sansfont: "Arial"
    # monofont: "Courier New"
    # mathfont: "TeX Gyre Termes Math"
